### PR TITLE
Update rustc.conf to fix #100

### LINKED ISSUE #100: Rustc bootstrap should not download a binary rustc tarball
But re-use the system rustc instead

### PR DESCRIPTION
**Pull request by pro465**
trying to fix #100

NOTE: tested it on Termux and it works atleast on my phone.

### CODE REVIEW

**Comment by rxrbln** [comment]
Well, you need to work with the latest SVN sources, as the git mirror is not up-to-date and this issue already mostly solved. For a start rustc has a --local-rust option. which even is commented in the source. Historically enabling that did not build. It does so now, but it might not be the most reliable for some rust reason. This issue was about making rust bootstrap reliable not just one config option. Also: you really need to test your pull request before publishing them ;-)

**Comment by pro465** [comment]
so... should i close this PR?

**Comment by rxrbln** [comment]
> so... should i close this PR?

I can do this with this comment: #100 is about reliable bootstrap w/ a local rustc compiler, not just one config option to enable it.

**Comment by rxrbln** [comment]
> so... should i close this PR?

I can do this with this comment: https://github.com/rxrbln/t2sde/issues/100 is about reliable bootstrap w/ a local rustc compiler, not just one config option to enable it.

**Comment by pro465** [comment]
ok,

btw, thank you for (unintentionally/indirectly) forcing me to learn `sed`! now i have another inspiration to Rewrite It In Rust :D

**Comment by Sruhvx-jpg** [comment]
@pro465  crazy thing to say my guy

**Pull request closed without merging**
