### PR TITLE
Update util-linux.desc

### PR DESCRIPTION
**Pull request by scsijon**
version path change missed

### CODE REVIEW

**Comment by rxrbln** [comment]
Why does this util-linux update also update pciutils and bacon? And why don't they have a Download checksum?

**Comment by rxrbln** [comment]
the pciutils id change is a no-go. While upstream handles this rather unprofessionally, we snapshot and synced it to the mirrors on a known date bringing order in this chaos. This is only failed recently as I had not yet had enough time to re-setup mirror sining. The style should be either kept, or we switch to the hwdata package to provide versioned pci ids.

**Comment by scsijon** [comment]
it isn't, there are three independant fixes, that's the way github seems 
to have linked them for some reason, I did add github comments you 
should be able to see to explain each of them. The bacon change to zero 
is because the sum is incorrect and I couldn't remember which one you 
were using to put the correct one in. i'll hold off for the other fixes 
until I review how t2 packaging is formatted. I've also a few new 
packages for you to consider, such as the limine bootloader.

**Comment by rxrbln** [comment]
> it isn't, there are three independant fixes, that's the way github seems
> to have linked them for some reason, I did add github comments you
> should be able to see to explain each of them.

You use git and GitHub wrong. Like in any other project you need to push a tree or branch with just the changes for that one issue.

> The bacon change to zero
> is because the sum is incorrect and I couldn't remember which one you
> were using to put the correct one in. i'll hold off for the other fixes

scripts/Create-CkSumPatch but I just run scripts/Commit even when I don't want to instantly want to commit it to have it updated. scripts/Update-Pkg will also run that internally after a successful download. Basically every script use case will do that automatically. I think you want to stop editing such updates manually ;-)

> until I review how t2 packaging is formatted. I've also a few new
> packages for you to consider, such as the limine bootloader.

Honestly, git issues will be too much overhead and annoying for both, you and me. Patches via email or any other means like pinging someone of us on discord will be much faster for everyone, ... Personally, I would use GitHub issues only for major work items, or long term todo reminders.

**Pull request closed without merging**
